### ISSUE TITLE
Independent blur and contrast settings for home screen and lock screen using the same image source for the wallpaper changer.

### ISSUE THREAD

**Issue by padok** [you-apps/WallYou#188]
### Describe your suggested feature

I would like to be able to set the blur and contrast setting for the home screen and lock screen separately for the same image source. As far as I understand, the settings are oriented to the image source, so I could set a blurred Reddit image for my home screen and a non-blurred Bing image for my lock screen. What I would like to be able to do is set the Bing image for my lock screen and my home screen, but the home screen is blurred.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Due to the amount of work needed refactoring many parts of the app and UI to implement that, this is out of scope.

What I will do for now is to add a toggle for each wallpaper changer configuration to `Apply image filters` - which can be disabled in order to neither blur, grayscale and change contrast when the image is applied automatically.
